import { test, expect, request, chromium } from "@playwright/test";
import fs from "fs";
import "dotenv/config";


//👩‍💻 📟🔐Authenticate via API  using the storage state generated by the fixture
//When to use:
//Your web application supports authenticating via API that is easier/faster 
// than interacting with the app UI.

/**
 * ┌────────────────────────────────────────────────────────────┐
 * │         Test Block: Uses storageState from saved file       │
 * └────────────────────────────────────────────────────────────┘
 *                   │
 *                   ▼
 *    Playwright auto-loads `apilogin.json` into browser context
 *                   │
 *                   ▼
 *    No need to perform UI login again — already authenticated
 *                   │
 *                   ▼
 *   Test navigates directly to `/myorders` and validates content
 *
 *  Fast, clean, and ideal for stable backend-auth flows!
 */


const authFile = "playwright/.auth/apilogin.json";

const API_URL = "https://api.practicesoftwaretesting.com";
const WEB_URL = "https://practicesoftwaretesting.com";

test.describe("Authenticated API Test", () => {
  test.beforeAll(async () => {
    fs.mkdirSync("playwright/.auth", { recursive: true });

    const apiContext = await request.newContext();

    // Step 1: Login via API
    const loginRes = await apiContext.post(`${API_URL}/users/login`, {
      data: {
        email: process.env.CUSTOMER_USER,
        password: process.env.CUSTOMER_PASS,
      },
    });

    expect(loginRes.ok()).toBeTruthy();

    const json = await loginRes.json();
    const token = json.access_token;

    expect(token).toBeTruthy();
    console.log("Token generated successfully");

    // Step 2: Open browser and create context
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();

    // Important:
    // Go to frontend URL because localStorage belongs to frontend origin
    await page.goto(WEB_URL);

    // Step 3: Set token into localStorage
    await page.evaluate((tokenValue) => {
      localStorage.setItem("auth-token", tokenValue);
    }, token);

    // Step 4: Save storage state
    await context.storageState({ path: authFile });

    await browser.close();
    await apiContext.dispose();

    // Debug
    const savedState = JSON.parse(fs.readFileSync(authFile, "utf-8"));
    console.log("Saved storage state:", savedState.origins);
  });



  test("customer sees my account page", async ({ browser }) => {
      const context = await browser.newContext({
    storageState: authFile,
  });
    const page = await context.newPage();
    await page.goto(`${WEB_URL}/account`);

    await expect(page).toHaveURL(/account$/);

    await page.waitForLoadState("networkidle");

    // Example validation
    // Update this based on actual page text
    await expect(page.locator("body")).toContainText("My account");
      await context.close();
  });
});