name: Playwright Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test-with-docker:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run Playwright tests inside Docker
      run: docker run --rm playwright-tests